DcrInEgoM_psid_Act  nobit 1 unit=rad/s scmin=-97.8282 scmax=0.994704 fmt=f
DcrInEgoM_v_Act  nobit 2 unit=m/s scmin=-1178.24 scmax=51.2262 fmt=f
DcrInEgoM_beta_Act  nobit 3 unit=rad scmin=-20.3706 scmax=1.21525 fmt=f
EgoSafe_st_LnrDrvDet  nobit 5 unit=NoUnit scmin=-47.3 scmax=5.5 fmt=f
DcrInEgoM_qlsv_Act  nobit 6 unit=NoUnit scmin=-3.2 scmax=1.6 fmt=f
DcrIn1ms_a_BrkPedDrv  nobit 8 unit=m/s² scmin=-178.248 scmax=30.4325 fmt=f
AVL_BRTORQ_SUM  nobit 1 unit=Nm scmin=-159320 scmax=31864 fmt=f
SnsAcpd_pct_Acpd  nobit 2 unit=% scmin=-2881.68 scmax=758.336 fmt=f
DcrInEgoM_agwFA_Ste  nobit 3 unit=rad scmin=-31.4669 scmax=9.08519 fmt=f
DcrInEgoM_qlsagwFA_Ste  nobit 4 unit=NoUnit scmin=-2.6 scmax=2.2 fmt=f
AVL_STEA_FTAX_WHL  nobit 5 unit=° scmin=-1706.09 scmax=617.347 fmt=f
EgoStea_agFA_Whl  nobit 6 unit=rad scmin=-28.9324 scmax=11.6197 fmt=f
AVL_STEA_FTAX_WHL_ERR_AMP  nobit 7 unit=° scmin=3.59371e-010 scmax=-3.90621e-010 fmt=f
EgoStea_agFA_WhlOfs  nobit 8 unit=rad scmin=-0.000272328 scmax=-7.87813e-005 fmt=f
EgoIn5ms_ag_ActPosnEpsCalTo  nobit 1 unit=rad scmin=-34.1 scmax=18.7 fmt=f
EgoStea_agFA_WhlErrAmp  nobit 2 unit=rad scmin=-33 scmax=19.8 fmt=f
DcrInEgoE_vch_Veh  nobit 3 unit=m/s scmin=-63.65 scmax=97.15 fmt=f
DcrInEgoM_ax_Act  nobit 4 unit=m/s² scmin=-290.575 scmax=199.642 fmt=f
DcrInEgoM_ay_Act  nobit 5 unit=m/s² scmin=-1036.48 scmax=767.154 fmt=f
SnsSitDet_ay_Ack  nobit 6 unit=m/s² scmin=-1216.38 scmax=991.543 fmt=f
DmcTqz_ay_Ack  nobit 7 unit=m/s² scmin=-1059.62 scmax=939.105 fmt=f
SnsSitDet_cw_IndExp  nobit 8 unit=NoUnit scmin=-1821.6 scmax=1821.6 fmt=f
DcrSfTqzLimBInd_b_IndAyE0  nobit 1 unit=- scmin=-25.3 scmax=27.5 fmt=f
DcrSfTqzLimBInd_b_IndCm  nobit 2 unit=- scmin=-24.2 scmax=28.6 fmt=f
DcrSfTqzLimBInd_b_IndCs  nobit 3 unit=- scmin=-23.1 scmax=29.7 fmt=f
DcrSfTqzLimBInd_b_IndSteSta  nobit 4 unit=- scmin=-22 scmax=30.8 fmt=f
~ DcrSfTqzLimB_tqz_LimMax  nobit 5 unit=Nm scmin=-1.82733e+006 scmax=2.82226e+006 fmt=f
~ DcrSfTqzLimB_tqz_LimMin  nobit 6 unit=Nm scmin=-1.71058e+006 scmax=2.5843e+006 fmt=f
DcrSfTqzLim_tqz_LimMax  nobit 7 unit=Nm scmin=-1.80494e+006 scmax=3.30156e+006 fmt=f
DcrSfTqzLim_tqz_LimMin  nobit 8 unit=Nm scmin=-1.63155e+006 scmax=2.96309e+006 fmt=f
DcrSfActGate_b_TqzErr  nobit 1 unit= scmin=-16.5 scmax=36.3 fmt=f
~ DcrSfActGate_tqz_SpNorm  nobit 2 unit=Nm scmin=-108329 scmax=254903 fmt=f
~ DcrSfActGate_ax_SpNorm  nobit 3 unit=m/s² scmin=-147.345 scmax=379.599 fmt=f
QU_FN_FDR  nobit 4 unit= scmin=-27584.8 scmax=84802.4 fmt=f
TarPressureFkrWheelFL  nobit 5 unit=bar scmin=-852.505 scmax=2867.52 fmt=f
TarPressureFkrWheelFR  nobit 6 unit=bar scmin=-429.11 scmax=1630.62 fmt=f
TarPressureFkrWheelRL  nobit 7 unit=bar scmin=-386.199 scmax=1673.53 fmt=f
TarPressureFkrWheelRR  nobit 8 unit=bar scmin=-343.288 scmax=1716.44 fmt=f
DcrSfActGate_st_ErrDeb  nobit 1 unit=NoUnit scmin=-7.7 scmax=45.1 fmt=f
~ DcrSfActGate_tqcFA_EmSp  nobit 2 unit=Nm scmin=-1977.99 scmax=12918.6 fmt=f
~ DcrSfActGate_tqcRA_EmSp  nobit 3 unit=Nm scmin=-2861.58 scmax=23155.5 fmt=f
DcrSfActGate_qlsst_Shdn  nobit 4 unit=NoUnit scmin=-4.4 scmax=48.4 fmt=f
Qualifier_Function_FkrPressureInterface  nobit 5 unit= scmin=6.3 scmax=49.5 fmt=f
Qualifier_Function_IbPressureInterface  nobit 6 unit= scmin=7.2 scmax=50.4 fmt=f
DcrIn1ms_qls_FctIbPressIface  nobit 7 unit=NoUnit scmin=1.8 scmax=11.4 fmt=f
DCR_FUSA_DBG_SIG  nobit 8 unit= scmin=0 scmax=52.8 fmt=f
